### ISSUE TITLE
Multiple-Users tracking Contributions

### ISSUE THREAD

**Issue by Tready07** [rclim95/StardewValleyMods#5]
# Tracking contributions across all the users in Stardew
After consideration, we decided it would be easier if everyone tracks contributions that way everyone can view contributions. Also the host won't be overloaded with sending everyone previous contributions.

TODO:

- [ ] Everyone create their own SQLite database.
- [ ] Everyone send their contributions to the other users.
- [ ] Everyone record contributions and log it into their database.
